### ISSUE TITLE
Default scopes that use `allow_blank: true` override all preceding scopes

### ISSUE THREAD

**Issue by alecvn** [heartcombo/has_scope#120]
I have some scopes that I need to apply at all times on my `index` method, which I don't want to be available as a url-based filter.

If I use `has_scope` with a `default` value and `allow_blank: true`, it overrides (basically removes) those scopes.

Here is an example:
```
has_scope :filter_by_archived, default: false, allow_blank: true

def index
  apply_scopes(MyModel.filter_by_some_entity(current_user.some_entity_id)).all
end
```

I always want to filter `MyModel` by the `current_user`'s entity and not have that available through url parameters.  Additionally, I want to `filter_by_archived` by default, where the default value is `false`, and then when a user wants to see archived records they can append `?filter_by_archived=true`.

The problem is that the combination of having a `default` value and `allow_blank: true` removes the `filter_by_some_entity` query entirely.

**Comment by carlosantoniodasilva** [comment]
Can you show the scopes that each of these "filters" represent?

Also, it seems like `filter_by_archived` is a boolean type, you might want to check https://github.com/heartcombo/has_scope#boolean-usage for how to set those up.
