### ISSUE TITLE
Problem with apply_scopes with relation

### ISSUE THREAD

**Issue by clubbavi** [heartcombo/has_scope#121]
Hello,

I am using Rails - 6.0.2 & Ruby - 2.6.6
I have something like this:

`Accounts has_many users, so I call the apply_scopes on account.users`

This seems to be not working. It doesn't return the correct result. If I pass directly User model, then it works.
Is there any way I can apply this way 

`apply_scopes(account.users)`

**Comment by carlosantoniodasilva** [comment]
I have just tested this through an association (`apply_scopes(@post.comments).all`) and it worked okay, I didn't run into any issues.

Can you give more examples of what's not working? Maybe some sample code of your has_scope and model scope declarations?
