### ISSUE TITLE
Boolean Documentation is Misleading

### ISSUE THREAD

**Issue by atomaka** [heartcombo/has_scope#90]
The [boolean usage documentation](https://github.com/plataformatec/has_scope#boolean-usage) shows an example of setting a default value on a scope

```
has_scope :visible, type: :boolean
has_scope :active, type: :boolean, allow_blank: true

# and models with
scope :visible, -> { where(visible: true) }
scope :active, ->(value = true) { where(active: value) }
```

This leads me to believe that I should be able to implement the code above and be able to call `/resource?active` and receive have the scope processed with `true` as the value. However, the scope receives the value `false`.

**Comment by andrhamm** [comment]
In `/resource?active` Rails will always parse `active` as nil, which is a falsey value. Furthermore, the docs say:

> `'true'` and `'1'` are parsed as `true`, everything else as `false`

**Comment by gokulsupersaiyan** [comment]
@andrhamm Can we add this in documentation also?.

**Comment by carlosantoniodasilva** [comment]
Added a note to the readme to clarify that behavior, let me know if that works well for you all, thanks.
