### ISSUE TITLE
belongs_to scope

### ISSUE THREAD

**Issue by masudhossain** [heartcombo/has_scope#99]
I was able to apply a scope for a has_many associations, but can't figure out belongs_to association. 

This is what i used for `league has_many :champions, through: :league_champions`
`scope :by_champion, -> champion {League.joins(:league_champions).where(league_champions: {id: LeagueChampion.where(champion: Champion.where(id: champion))})}`

I wanna now be able to do the same but for `League belongs_to user` association. And filter by `user.price`. 

Any idea?

**Comment by andriymosin** [comment]
What you're asking here is not related to has_scope gem, it's basically about how scopes in ActiveRecord works. However, answering your question the code might looks like this:

League.rb
```
belongs_to :user
scope :by_price, -> (the_price) { joins(:user).where(user: { price: the_price }) }
```

LeaguesController.rb
`has_scope :by_price`
